docker: &sid
  - image: debian:sid
    environment:
      TZ: '/usr/share/zoneinfo/Asia/Istanbul'
version: 2
jobs:
  tests:
    docker: *sid
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt-get update -y
            apt-get install -y git curl ca-certificates shellcheck bats file
      - run:
          name: Lint with Shellcheck
          command: |
            shellcheck $(find -type f -and -not -path './.git/*' | xargs file --mime-type | grep text/x-shellscript$ | cut -f1 -d:)
      - run:
          name: Test with Bats
          command: bats tests
  legacy:
    docker:
      - image: debian:stretch
        environment:
          TZ: '/usr/share/zoneinfo/Asia/Istanbul'
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt-get update -y
            apt-get install -y git curl ca-certificates
      - run:
          name: Install legacy ruby version
          command: |
            PATH=$PWD:$PATH

            rubian install 2.1
            for prefix in /opt/rubies/*; do
              "$prefix"/bin/ruby -v
            done
            ruby -v
  latest:
    docker: *sid
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt-get update -y
            apt-get install -y git curl ca-certificates
      - run:
          name: Install latest ruby version
          command: |
            PATH=$PWD:$PATH

            rubian install latest
            for prefix in /opt/rubies/*; do
              "$prefix"/bin/ruby -v
            done
            ruby -v
workflows:
  version: 2
  test-and-build:
    jobs:
      - tests
      - legacy:
          requires:
            - tests
          filters:
            branches:
              only: master
      - latest:
          requires:
            - tests
          filters:
            branches:
              only: master
