docker: &docker
  - image: debian:sid
    environment:
      TZ: '/usr/share/zoneinfo/Asia/Istanbul'
version: 2
jobs:
  dependencies:
    docker: *docker
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt-get update -y
            apt-get install -y git curl ca-certificates shellcheck bats file
  tests:
    docker: *docker
    steps:
      - run:
          name: Lint with Shellcheck
          command: |
            shellcheck $(find -type f -and -not -path './.git/*' | xargs file --mime-type | grep text/x-shellscript$ | cut -f1 -d:)
      - run:
          name: Test with Bats
          command: bats tests
  ruby-build:
    docker: *docker
    steps:
      - run:
          name: Install and uninstall all suites
          command: |
            ./rubian install stable unstable legacy
            for prefix in /opt/rubies/*; do
              "$prefix"/bin/ruby -v
            done
            ruby -v
workflows:
  version: 2
  test-and-ruby-build:
    jobs:
      - dependencies
      - tests:
          requires:
            - dependencies
      - ruby-build:
          requires:
            - tests
          filters:
            branches:
              only: master